export const SUPPORT_FORM_SUBMIT = "SUPPORT_FORM_SUBMIT";
export const ADD_TO_CART = "ADD_TO_CART";
export const EDIT_CART_QUANTITY = "EDIT_CART_QUANTITY";
export const REMOVE_CART_ITEM = "REMOVE_CART_ITEM";
